### ISSUE TITLE
automatic build

### ISSUE THREAD

**Issue by hayguen** [jorgem-seq/ExtIO_RTL#4]
Hi,
this is NO issue .. but FYI:

i've forked your tree with some additions: https://github.com/hayguen/ExtIO_RTL
the relevant changes are documented there

should i create a pull request?

regards,
hayati

**Comment by jorgem-seq** [comment]
Hi Hayati, if you plan to keep it compiling/working with newer build tools I'd prefer to just add:

> Notice: The development of ExtIO_RTL continues in https://github.com/hayguen/ExtIO_RTL

and then archive this repository, let me know.

Some notes:
[src/rtlsdr.def](https://github.com/hayguen/ExtIO_RTL/blob/master/src/rtlsdr.def) can be deleted it's for Mingw-w64: 03581038e4fdca971990a8fc4a7c6c81eae08980
The "Bias Tee" option is not saved/restored and it's always reset during setup for safety.
The branch switch needs more work/testing that I'm not going to do, other than that for me it's finished.

Thanks.

**Comment by hayguen** [comment]
Hi Jorge,

i would like to see more features of https://github.com/hayguen/extio_rtl_tcp in ExtIO_RTL .. ideally someone else would develop/port, cause i'm lacking time. Keeping compiling should be possible "somehow" - at least on request. The automatic build of github actions is working for now.

* What i still cared: compatibility with Windows XP for OMs with ancient computers!
* MinGW build should be kept running - although i had removed the Makefiles. But i'd also prefer to get it built with cmake ..
* Win64: is there any 64-bit SDR program with ExtIO interface?

regards,
Hayati

**Comment by hayguen** [comment]
> The "Bias Tee" option is not saved/restored and it's always reset during setup for safety.

Can you explain, what could go wrong?

**Comment by jorgem-seq** [comment]
With keeping it compiling I meant that things may need to be updated for newer versions of VS, cmake or librtlsdr and that requires work.

I tested the 64-bit dll with a modified version of SDR# https://github.com/SDRSharpR/SDRSharper/tree/master/Binaries/
On launching an error message shows up "Error setting audiodevices...", PortAudio_x64.dll needs to be replaced with the one from https://airspy.com/downloads/sdrsharp-x64.zip
Rename the dll and replace sdrsharp-x64\PortAudio.dll -> Release\PortAudio_x64.dll. I don't know where it comes from, try it on a VM if you can.

Bias tee is disabled in case that a previous tool left it enabled, I don't know if it this is correct and that's why it's in the testing branch.
https://github.com/jorgem-seq/ExtIO_RTL/blob/9db110f235e37c0996c7f383ca2ad06f70f0775b/src/ExtIO_RTL.cpp#L639-L641

What could go wrong? Someone enabling bias tee on a DC shorted antenna, currently it is disabled on startup and the user has to voluntarily tick the option for that to happen.

**Comment by hayguen** [comment]
> With keeping it compiling I meant that things may need to be updated for newer versions of VS, cmake or librtlsdr and that requires work.

OK. should be possible.

> with a modified version of SDR#

i know the author of SDR#. i'm not going to support illegal clones


> Someone enabling bias tee on a DC shorted antenna, currently it is disabled on startup and the user has to voluntarily tick the option for that to happen

there are dongles, which have ALWAYS bias tee on, e.g. Nooelec!? might these get damaged on a shortcut?

**Comment by jorgem-seq** [comment]
Thank you for reply, I added the reference in the readme and now I'm closing issues and archiving repositories.

Regards,
Jorge.
